// Common
export const RESET = "RESET";

// UI
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

// User
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

// Home
export const FETCH_LIST_ROOM = "FETCH_LIST_ROOM";
export const FETCH_LIST_ROOM_SUCCESS = "FETCH_LIST_ROOM_SUCCESS";
export const UPDATE_ROOM_SEARCH = "UPDATE_ROOM_SEARCH";
export const FETCH_ROOM = "FETCH_ROOM";
export const FETCH_ROOM_SUCCESS = "FETCH_ROOM_SUCCESS";

// Order
export const FETCH_SELECTED_BOOK_ROOM = "FETCH_SELECTED_BOOK_ROOM";
export const FETCH_SELECTED_BOOK_ROOM_SUCCESS = "FETCH_SELECTED_BOOK_ROOM_SUCCESS";
export const BOOK_ROOM = "BOOK_ROOM";

// Admin
export const FETCH_ADMIN_INFO = "FETCH_ADMIN_INFO";
export const FETCH_ADMIN_INFO_SUCCESS = "FETCH_ADMIN_INFO_SUCCESS";
export const SAVE_ADMIN_INFO = "SAVE_ADMIN_INFO";
export const FETCH_ADMIN_LIST_HOST = "FETCH_ADMIN_LIST_HOST";
export const FETCH_ADMIN_LIST_HOST_SUCCESS = "FETCH_ADMIN_LIST_HOST_SUCCESS";
export const FETCH_ADMIN_LIST_ORDER_HISTORY = "FETCH_ADMIN_LIST_ORDER_HISTORY";
export const FETCH_ADMIN_LIST_ORDER_HISTORY_SUCCESS = "FETCH_ADMIN_LIST_ORDER_HISTORY_SUCCESS";

// Host
export const FETCH_HOST_INFO = "FETCH_HOST_INFO";
export const FETCH_HOST_INFO_SUCCESS = "FETCH_HOST_INFO_SUCCESS";
export const SAVE_HOST_INFO = "SAVE_HOST_INFO";
export const FETCH_HOST_LIST_ORDER = "FETCH_HOST_LIST_ORDER";
export const FETCH_HOST_LIST_ORDER_SUCCESS = "FETCH_HOST_LIST_ORDER_SUCCESS";
export const FETCH_HOST_LIST_ORDER_HISTORY = "FETCH_HOST_LIST_ORDER_HISTORY";
export const FETCH_HOST_LIST_ORDER_HISTORY_SUCCESS = "FETCH_HOST_LIST_ORDER_HISTORY_SUCCESS";

// Customer
export const FETCH_CUSTOMER_INFO = "FETCH_CUSTOMER_INFO";
export const FETCH_CUSTOMER_INFO_SUCCESS = "FETCH_CUSTOMER_INFO_SUCCESS";
export const SAVE_CUSTOMER_INFO = "SAVE_CUSTOMER_INFO";
export const FETCH_CUSTOMER_ORDER = "FETCH_CUSTOMER_ORDER";
export const FETCH_CUSTOMER_ORDER_SUCCESS = "FETCH_CUSTOMER_ORDER_SUCCESS";
export const FETCH_CUSTOMER_ORDER_HISTORY = "FETCH_CUSTOMER_ORDER_HISTORY";
export const FETCH_CUSTOMER_ORDER_HISTORY_SUCCESS = "FETCH_CUSTOMER_ORDER_HISTORY_SUCCESS";
export const DELETE_CUSTOMER_ORDER = "DELETE_CUSTOMER_ORDER";
